### ISSUE TITLE
fix: `npm run deploy evm/nft-linker local` failed to execute

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelar-examples#123]
The command didn’t execute completely; it got stuck for some reason.

```
> axelar-examples@1.0.0 execute
> node scripts/runExecute evm/nft-linker local Avalanche Fantom

--- Initially ---
Token that was originally minted at Avalanche is at Avalanche.
Token that was originally minted at Fantom is at Fantom.


After retrying, it returned:

> axelar-examples@1.0.0 execute
> node scripts/runExecute evm/nft-linker local Avalanche Fantom

--- Initially ---
Token that was originally minted at Avalanche is at .
Token that was originally minted at Fantom is at Fantom.
/Users/mac/Desktop/GIT/axelar/axelar-examples/scripts/libs/utils.js:125
        CHAINS.TESTNET[source.name.toUpperCase()],
                              ^

TypeError: Cannot read properties of undefined (reading 'name')
    at calculateBridgeFee (/Users/mac/Desktop/GIT/axelar/axelar-examples/scripts/libs/utils.js:125:31)
    at Object.execute (/Users/mac/Desktop/GIT/axelar/axelar-examples/examples/evm/nft-linker/index.js:83:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeEVMExample (/Users/mac/Desktop/GIT/axelar/axelar-examples/scripts/libs/execute.js:65:5)

Node.js v18.13.0
```

**Comment by Marcia12sdf** [comment]
Aleksandra
